language: node_js
node_js:
- 8.9.4
deploy:
  provider: npm
  email: junrai82@gmail.com
  on:
    tags: true
  api_key:
    secure: LyIT8M3N7VlrTydgLwJ0zB6YXwLS8b/4tP9FKi1yDXgazJ2nyJGZqzGFstjmP/FCD8iQ15EVrvWoBU5vIpSsRxHuOX9VVzx9efaKNIEDeaIpvdXw76KHOXLFsoeCG/XTyZq1KnLSzo+9l6ZlkRD3kCZKHpN4S/H/UmXRsmH6TYqimq5hPcLk8ngB3dFFGHH2C00LAV6n4BN1RwY9H6iPNA+iDzrTzakcpk+e2lflJ4K3F/SXAm7u4VAmx5gE5Kwjn3YO3LXIWDgYyRQrSR0JhGOVy3sdx88A8WsvOKsCgqXdV1QmmfkjQWQjQ4KTcqaXhjaO0ndsreQ5bJ4ighqb23efaRLAD/PppZpQb0GkJ3mEc//MxT3MaAU8MhOhoL3xgPLnmrDQshjxfcgGZVrGl0l5FcIxJ7+9cKu0GBM+pikK5VFrN2OPLdkdjja4d/TzTrTJj9ECd/xY3leNu+OSyC1jwRj6K5ivX4PUL6Z+BThy5w5A+eFlpvTr1vB4uhbjKQEFn5X5OmAT/34OetFqh2udk7qGYYY6Mfw+xgyqIKpmaXH4A+Lb4aPvw1eklLzw22i1Cf7oxzDmgnIviOlaGt36IQKGfBAFLnIOrrLQLriXRXtdAoaD7Rb1CQzEHlvATKUonAgucSZmRvWPG3xjIlU/RlFZtFF03/zEoUUfAe4=
