language: node_js
node_js:
- 8.9.4
deploy:
  provider: npm
  email: junrai82@gmail.com
  on:
    tags: true
  api_key:
    secure: gjhR+KAuVuPDxWyWPnzPYwZ8wP+5WcArjD5MONSgU+ATnTyJ83+StP8LV78pqaSHVW+EfNitkZPP3fzXQWbNtSMWOiD3Ivm2eiq894XyIV0dJgFqdwHEjcYSHXnKPGJy7N5J/lnERsG5S6X/piXUd9aZ4x4A1jSrEYdhBxgylryXKxX4NrimeMKBCLZ3UR5l81/fPcM1QhiXpDuiI5JmJ1z2VL25lzpPtedLwl8tWdrlyatHH+RM5BpegNIPO2uWZF62cQjBTcUzv+WuHPrbftK7S5Bva36RH+6vWvNJMDy3/6UPbqKfMr2NN/9eL9Rn6KNBidlT15Jzifd+Q966CdLacJixnFH57EKOdFObASFs6X5RCzmMTZhtZ1pxfmERSZtipNdpIgU+6r6PqeDOfwiG35D+5STql+wtCHaCQYodprKJUrRQU8IZte1T9mgAu6L4enVjK33pFS8T8Bkv8aL3KhFSpeqrZKnFU9y73Ar5ZCGitoR5Td599tGk+DOEKjNuVASnse7JzILcZEbMt1hb2ChlpJW2Rmvos9dZSWmwwJWWgywC3guOeU5cWU3vET6aA8Ud/vsydXDoTBTqt5tJ+KEseDgWqAPPlU3NdSPViAnZDc2vtGrdplALP1wVE6AlRdwIkSyPXPhaf3tlLqyC2HjiMlXLut8j6VxfpxI=
